import Navbar from '@/components/Navbar/Navbar';
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/Footer/Footer';
import { ThemeProvider } from '@/context/ThemeContext';
import AuthProvider from '@/components/AuthProvider/AuthProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ThemeProvider>
      <AuthProvider>
        <div className="mx-auto p-4">
          <Navbar />
          <div className="mt-8">{children}</div>
          <Footer />
        </div>
        </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}